### ISSUE TITLE
Support a query interface in the dashboard

### ISSUE THREAD

**Issue by netomi** [eclipse-csi/otterdog#200]
The query interface should allow to find projects / repositories ... in all monitored projects that have certain settings.

Ideally the query would be done via graphql.

**Comment by mbarbero** [comment]
We're done here, no?

**Comment by netomi** [comment]
basic stuff works, but still needs some love and documentation.

**Comment by netomi** [comment]
a basic version is there, closing for now and we will improve this over time.
