### ISSUE TITLE
Scope commands

### ISSUE THREAD

**Issue by mbarbero** [eclipse-csi/otterdog#211]
Currently, the commands for Otterdog, such as verify, merge, etc., are not scoped. They can be placed anywhere within the comment body as long as they start with a `/`. This approach could potentially lead to confusion, unintended consequences, or even conflicts with other applications.

This ticket aims to discuss the adoption of scoped commands, similar to how Dependabot operates (https://docs.github.com/en/code-security/dependabot/working-with-dependabot/managing-pull-requests-for-dependency-updates#managing-dependabot-pull-requests-with-comment-commands), for example:

```
@otterdog verify
@otterdog merge
@otterdog help
```

Thoughts?

**Comment by netomi** [comment]
Sounds reasonable. I was already thinking of applying something similar to dependabot

**Comment by netomi** [comment]
Using @otterdog is not a good idea, as it will tag the user otterdog, which exists:

https://github.com/otterdog

**Comment by netomi** [comment]
Some other prefixes that might work:

- !
- .

# should not be used imho as it is used to reference Tickets / PRs
