### ISSUE TITLE
Support creating files in a repo that follows a template

### ISSUE THREAD

**Issue by netomi** [eclipse-csi/otterdog#222]
Some user request:

it would be nice to support creating files from templates in all repos, e.g. CODE_OF_CONDUCT.md or workflow files that should be present in all repos with slight changes.

**Comment by netomi** [comment]
@gdams can you give some example what type of file you have in mind for such a template and how such a template would look like?

Are you familiar with jinja? Would it be acceptable to use jinja templates for that and what type of variable would be useful or needed? We could inject information about the project as variables, e.g. project name, github organization, repo name.

**Comment by netomi** [comment]
Here is one example of such a jinja template that we already use: https://github.com/EclipseFdn/.eclipsefdn-template/blob/main/.github/CODEOWNERS

**Comment by gdams** [comment]
Yeah I was thinking of things like `CONTRIBUTING.md` and certain github workflows that we want to ensure are present in specific repos

**Comment by netomi** [comment]
implemented by blueprints with type required_file
