### ISSUE TITLE
JSONNet Example for use of "template repo"

### ISSUE THREAD

**Issue by stbischof** [eclipse-csi/otterdog#242]
Most of the repos looks the same

```
 orgs.newRepo('%__THE_REPO_NAME__%') {
      allow_squash_merge: false,
      allow_update_branch: false,
      delete_branch_on_merge: false,
      dependabot_security_updates_enabled: true,
      description: "%__THE_REPO_DESCRIPTION__%",
      has_wiki: false,
      variables: [
        orgs.newRepoVariable('SONAR_ORGANIZATION') {
          value: "eclipse-daanse",
        },
        orgs.newRepoVariable('SONAR_PROJECT_KEY') {
          value: "eclipse-daanse_%__THE_REPO_NAME__%",
        },
      ],
      branch_protection_rules: [
        orgs.newBranchProtectionRule('main') {
          required_approving_review_count: 0,
          requires_linear_history: true,
          requires_strict_status_checks: true,
        },
      ],
    },
```

The only diff is:
- %__THE_REPO_NAME__%
- %__THE_REPO_DESCRIPTION__%

would me great if jsopnnet could help me by reusing existing repo:

```
 orgs.newRepo: self.templaeRepo { name: "Foo" ,description "Bar" },

```

Could you provide support/examples?

**Comment by mbarbero** [comment]
One of Jsonnet's strengths is the ability to define functions that reuse or extend existing functions. You can see an example of this in the [Adoptium Jsonnet settings](https://github.com/adoptium/.eclipsefdn/blob/main/otterdog/adoptium.jsonnet#L14).

Please let us know if you need more information or support with this.

**Comment by netomi** [comment]
Another nice example can be found here: https://github.com/eclipse-vertx/.eclipsefdn/blob/main/otterdog/eclipse-vertx.jsonnet#L10

**Comment by netomi** [comment]
To dynamically create strings from other properties you can use some build in functions of jsonnet, again the adoptium project does something like that here: https://github.com/adoptium/.eclipsefdn/blob/main/otterdog/adoptium.jsonnet#L45

Using the playground at https://daanse.org/.eclipsefdn/playground/ should also allow you to experiment with that.

**Comment by stbischof** [comment]
Thx. i looked for this!!
