### ISSUE TITLE
Custom messages for specific actions

### ISSUE THREAD

**Issue by heurtematte** [eclipse-csi/otterdog#318]
I would like otterdog to implement custom messages for specific actions depending on the organization configuration.

E.g: with this ticket https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5267

When otterdog create a new repository, I would like otterdog to add a message to the PR after a repository newly created with something like: 

```
The GitHub repo https://github.com/eclipse-<project_id>/some_repo has been created. Committers will gain access to it once the sync script runs (~2h).
```

Note: Implement a pre-action message or a post-action message, to order correctly messages and actions.

**Comment by netomi** [comment]
there is already a pre-add hook we could also add a post-add hook.

**Comment by matbmoser** [comment]
Thank you for the feature <3

**Comment by netomi** [comment]
You see how it looks like in this PR: https://github.com/eclipse-sumo/.eclipsefdn/pull/4

I added an additional linebreak before the warning as otherwise it looks too packed.
