### ISSUE TITLE
Official container?

### ISSUE THREAD

**Issue by tykeal** [eclipse-csi/otterdog#319]
My team is currently considering Otterdog for managing a lot GitHub repos across several organizations and we noticed that there is a Dockerfile defined but there doesn't seem to be a released container anywhere. None of the docs talk about how to use the container and I have not been able to figure it out myself.

Could I get a pointer? We're hoping to find a way to do some automation around using Otterdog via GitHub Actions and having an official container along with information on how to use it would be very useful!

**Comment by netomi** [comment]
A docker container is available here: https://github.com/eclipse-csi/otterdog/pkgs/container/otterdog

Every push to the main branch update the latest snapshot version and releases are also published there.

If you wanna use otterdog, we probably should document / explain the initial setup. Its not too much hassle but the documentation is lacking in this regard as we were using that only for ourselves so far.

btw. take a look at the dashboard at https://otterdog.eclipse.org to get a feeling on its current features. We also started to work on policies and blueprints (see https://otterdog.readthedocs.io/en/latest/reference/blueprints/)

**Comment by netomi** [comment]
So what things are required for an otterdog instance:

- define a default config, ours can be found at https://github.com/EclipseFdn/otterdog-defaults/
- setup a config repo to control which organizations can actually use your instance and for general setup, ours can be found at https://github.com/EclipseFdn/otterdog-configs/
- deploy the service to a kubernetes cluster, we use openshift, the deployment descriptors can be found here: https://github.com/EclipseFdn/otterdog-configs/tree/main/k8s (this needs to be changed to a helm chart)

you will need some credential store to store some credentials that the cli uses, currently supported are pass and bitwarden.

fyi: there is a cli tool and a GitHub App. So far they operate fully independent of each other as this is how the tool evolved, but in the long term the cli tool should connect to the GitHub App to further reduce the need to store additional credentials in the credential store.

I would be happy to give an introduction how its being used and operated at the EF. There are certainly some rough edges, but we would be happy to make the deployment as simple as possible for others to use as well.

**Comment by tykeal** [comment]
Is there some way to essentially consume it without having to keep a k8s cluster up somewhere? Our real desire is to have configuration and enforcement based on changes to the repository be propagated via a GitHub Actions run.

We currently do something very much like that with Jenkins systems using Jenkins Job Builder and our Gerrit systems using custom tooling we created. We're needing to start managing a lot more GitHub orgs though and I want to make sure my team is doing it all the same _and_ let our communities more self-sufficiency and right now the debate is between Otterdog and [Clowarden](https://github.com/cncf/clowarden) but we really don't want to be keeping all the infra (including DB) for stuff.

**Comment by tykeal** [comment]
If some sort of 30 minute meeting would work, I would be happy to do that as well. I can be reached at agrimberg@linuxfoundation.org for scheduling it :)

**Comment by netomi** [comment]
v0.9.0 has been released: https://pypi.org/project/otterdog/0.9.0/

You can install it via pipx install otterdog .
In order to access the web ui you will also need to run `otterdog install-deps` afterwards which will download and install the firefox browser for use with playwright.

Apart from that only git is needed as dependency and then the bitwarden or pass cli tools depending on your setup.

As a test, I did use the cli myself to manage one of my organizations, this is the setup I used:

```json
{
  "defaults": {
    "jsonnet": {
      "base_template": "https://github.com/eclipse-csi/otterdog#examples/template/otterdog-defaults.libsonnet@main",
      "config_dir": "orgs"
    }
  },
  "organizations": [
    {
      "name": "tinygears",
      "github_id": "TinyGearsOrg",
      "credentials": {
        "provider": "bitwarden",
        "item_id" : "118276ad-158c-4720-b68d-af8c00fe3481"
      }
    }
  ]
}
```

Created a PAT with the required scopes and added the credentials to bitwarden.
After that running:

`otterdog import tinygears`

imports the current live configuration and you can start playing around with the config.
No config repo is needed, you can chose to store the configuration wherever you want, however when you want to use the operations `push-config` and `fetch-config` you need to create such a repo. You could also reuse the `.github` repo for that purpose. In our case, we define the config repo in the default config and it gets automatically created when running `apply` the first time.

**Comment by netomi** [comment]
In another project we already successfully migrated to using uv: https://github.com/eclipse-csi/octopin

At some point in the near future we probably wanna do the same for this project.  Right now there are no real plans to re-provide a docker image as it would not give much benefit imho.

The main obstacle for the docker image was the handling of local files and a wrapper script. If others are really willing to use the cli for their own project and need a docker image, we can certainly reevaluate.
